// Planes destacados de Barcelona y Cataluña, con fechas comprobadas en sus webs o en guías de la ciudad.
// Se actualiza cada mes (tarea programada): añade lo nuevo, corrige fechas y quita lo que ya pasó hace más de un mes.
// Campos: id, n (nombre), from/to (AAAA-MM-DD) o days (lista de días sueltos), lugar, precio, gratis, tipo, url, nota, aprox (fecha sin confirmar).
// Tipos: fiesta, musica, comida, cine, cultura, mercado, deporte, navidad, ofertas, ciudad.
'use strict';
const PLANES_ACTUALIZADO = '2026-09-30';
const PLANES_BCN = [
  { id: 'oktoberfest-26', n: 'Oktoberfest Barcelona', days: ['2026-10-01', '2026-10-02', '2026-10-03', '2026-10-04', '2026-10-08', '2026-10-09', '2026-10-10', '2026-10-11'], lugar: 'Fira de Barcelona Gran Via', precio: 'Entrada de pago', tipo: 'comida', url: 'https://www.oktoberfest-barcelona.es/', nota: 'De jueves a domingo. Jue 17–23 h, vie 17–1 h, sáb 12–1 h, dom 12–23 h.' },
  { id: 'bravas-26', n: 'Mahou Bravas Fest', from: '2026-10-02', to: '2026-10-04', lugar: 'Poble Espanyol (Montjuïc)', precio: 'Gratis si vives en Cataluña (descarga la entrada); Fast Pass desde 8,50 €', gratis: true, tipo: 'comida', url: 'https://www.bravasfest.com/', nota: 'Los mejores bares compiten por las bravas, con música en directo. Vie 18–24 h, sáb 12–24 h, dom 12–22 h. Aforo limitado.' },
  { id: 'vermut-26', n: 'Vermut & Soul', from: '2026-10-02', to: '2026-10-04', lugar: 'Port Olímpic', precio: '5–32 €', tipo: 'comida', url: 'https://irbarcelona.org/barcelona-october/', nota: 'Feria del vermut con catas y música.' },
  { id: 'disc-26', n: 'Fira Internacional del Disc', from: '2026-10-02', to: '2026-10-04', lugar: 'Estació del Nord', precio: 'Entrada de pago', tipo: 'musica', url: 'https://www.barcelona.cat/capdesetmana/es/moduls/guia/41a-fira-internacional-del-disc-de-barcelona-99400096517', nota: 'Vinilos, CD y rarezas. Vie 15–20:30 h, sáb 10–20:30 h, dom 10–19 h.' },
  { id: 'palo-26', n: 'Palo Market Fest', days: ['2026-10-03', '2026-10-04', '2026-11-07', '2026-11-08', '2026-11-21', '2026-11-22', '2026-12-05', '2026-12-06'], lugar: 'C/ Pellaires 30, Poblenou', precio: '6,50 €', tipo: 'mercado', url: 'https://palomarketfest.com/en/barcelona/calendar', nota: 'Mercado de diseño, ropa, comida callejera y música. 12–17 h y 17:30–22 h.' },
  { id: 'hostafrancs-26', n: 'Festa Major d’Hostafrancs', from: '2026-10-02', to: '2026-10-11', lugar: 'Hostafrancs', precio: 'Gratis', gratis: true, tipo: 'fiesta', aprox: true, url: 'https://blog.apartmentbarcelona.com/events-in-barcelona-october-2026-a-complete-guide/', nota: 'Fiesta mayor del barrio: mercado medieval, conciertos y actividades.' },
  { id: 'sarria-26', n: 'Festa Major de Sarrià', from: '2026-10-02', to: '2026-10-12', lugar: 'Sarrià', precio: 'Gratis', gratis: true, tipo: 'fiesta', aprox: true, url: 'https://blog.apartmentbarcelona.com/events-in-barcelona-october-2026-a-complete-guide/', nota: 'Gegants, castellers y correfoc.' },
  { id: 'revelat-26', n: 'Revela’t (fotografía analógica)', from: '2026-10-01', to: '2026-10-18', lugar: 'Vilassar de Dalt', precio: 'Muchas actividades gratis', tipo: 'cultura', url: 'https://irbarcelona.org/best-events-calendar-barcelona/' },
  { id: 'sitges-26', n: 'Festival de Cine de Sitges', from: '2026-10-08', to: '2026-10-18', lugar: 'Sitges (40 min en tren)', precio: 'Entradas por sesión', tipo: 'cine', url: 'https://irbarcelona.org/best-events-calendar-barcelona/', nota: 'Cine fantástico y de terror; la zombie walk suele ser un sábado.' },
  { id: 'boat-26', n: 'Barcelona Boat Show', from: '2026-10-14', to: '2026-10-18', lugar: 'Barcelona', precio: 'Entrada de pago', tipo: 'ciudad', url: 'https://irbarcelona.org/best-events-calendar-barcelona/' },
  { id: 'mercats-26', n: 'Mercat de Mercats', from: '2026-10-16', to: '2026-10-18', lugar: 'Plaça de les Glòries', precio: 'Entrada libre (degustaciones de pago)', gratis: true, tipo: 'comida', url: 'https://www.barcelona.cat/mercatdemercats/es', nota: 'La gran feria de los mercados: chefs, productores y tapas.' },
  { id: 'jazz-26', n: 'Festival Internacional de Jazz', from: '2026-10-16', to: '2026-12-23', lugar: 'Varias salas', precio: 'Según concierto', tipo: 'musica', url: 'https://jazz.barcelona', nota: 'Dos meses de conciertos por toda la ciudad.' },
  { id: 'creepy-26', n: 'Creepy Halloween Family', days: ['2026-10-17', '2026-10-18', '2026-10-24', '2026-10-25', '2026-10-31', '2026-11-01'], lugar: 'Poble Espanyol', precio: 'Entrada de pago', tipo: 'fiesta', url: 'https://poble-espanyol.com/actividad/halloween-en-el-poble/', nota: 'Halloween para ir con críos (o sin ellos).' },
  { id: 'cine350-26', n: 'Fiesta del Cine: entradas a 3,50 €', from: '2026-10-19', to: '2026-10-22', lugar: 'Cines de toda España', precio: '3,50 € la entrada', tipo: 'ofertas', url: 'https://www.fiestadelcine.com/', nota: 'Cualquier película de la cartelera. Venta anticipada desde el 14.' },
  { id: 'openhouse-26', n: '48h Open House Barcelona', from: '2026-10-24', to: '2026-10-25', lugar: 'Más de 200 edificios del área metropolitana', precio: 'Gratis', gratis: true, tipo: 'cultura', url: 'https://www.48hopenhousebarcelona.org/es/', nota: 'Edificios que normalmente no se pueden visitar. Algunos piden reserva.' },
  { id: 'inedit-26', n: 'In-Edit: documentales de música', from: '2026-10-29', to: '2026-11-08', lugar: 'Cines Mooby Aribau', precio: 'Entradas por sesión', tipo: 'musica', url: 'https://es.in-edit.org/en/', nota: 'El festival de cine documental musical de referencia.' },
  { id: 'santallucia-26', n: 'Fira de Santa Llúcia', from: '2026-11-27', to: '2026-12-23', lugar: 'Avinguda de la Catedral', precio: 'Gratis', gratis: true, tipo: 'navidad', aprox: true, url: 'https://es.firadesantallucia.cat/', nota: 'El mercado de Navidad más antiguo de la ciudad (el primer día puede cambiar).' },
  { id: 'manga-26', n: 'Manga Barcelona', from: '2026-12-05', to: '2026-12-08', lugar: 'Fira de Barcelona Gran Via', precio: 'Entrada de pago', tipo: 'cultura', url: 'https://www.manga-barcelona.com/es/info.cfm', nota: '9–20 h. Cosplay, conciertos de J-pop, comida japonesa.' },
  { id: 'reis-26', n: 'Fira de Reis de la Gran Via', from: '2026-12-15', to: '2027-01-06', lugar: 'Gran Via', precio: 'Gratis', gratis: true, tipo: 'navidad', url: 'https://irbarcelona.org/best-events-calendar-barcelona/' },
  { id: 'tomb-27', n: 'Els Tres Tombs de Sant Antoni', from: '2027-01-17', to: '2027-01-17', lugar: 'Sant Antoni', precio: 'Gratis', gratis: true, tipo: 'fiesta', url: 'https://irbarcelona.org/best-events-calendar-barcelona/', nota: 'Desfile de caballos y carruajes.' },
  { id: 'mwc-27', n: 'Mobile World Congress', from: '2027-03-01', to: '2027-03-04', lugar: 'Fira de Barcelona Gran Via', precio: '—', tipo: 'ciudad', url: 'https://www.barcelona-tourist-guide.com/es/eventos/comerciales-ferias/mobile-world-congress-barcelona.html', nota: 'Más gente, más tráfico y hoteles y restaurantes más caros esos días.' },
  { id: 'marato-27', n: 'Zurich Marató de Barcelona', from: '2027-03-14', to: '2027-03-14', lugar: 'Toda la ciudad', precio: 'Para verla, gratis', gratis: true, tipo: 'deporte', url: 'https://zurichmaratobarcelona.es/es/', nota: 'Cortes de tráfico por la mañana.' },
  { id: 'primavera-27', n: 'Primavera Sound', from: '2027-06-03', to: '2027-06-05', lugar: 'Parc del Fòrum', precio: 'Abonos y entradas', tipo: 'musica', url: 'https://irbarcelona.org/best-events-calendar-barcelona/' },
  { id: 'sonar-27', n: 'Sónar', from: '2027-06-17', to: '2027-06-19', lugar: 'Fira Montjuïc y Gran Via', precio: 'Abonos y entradas', tipo: 'musica', url: 'https://www.musicfestivalwizard.com/festivals/sonar-barcelona-2027/' },
  { id: 'cruilla-27', n: 'Cruïlla', from: '2027-07-07', to: '2027-07-10', lugar: 'Parc del Fòrum', precio: 'Abonos y entradas', tipo: 'musica', url: 'https://www.laganzua.net/conciertos/cruilla-festival-2027-weekend-barcelona-1016929' },
];
